package GUI;

import java.awt.Desktop;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.conexion;

public class alta extends javax.swing.JFrame {

    int conteo;
    int total;
    int limite;
    String idBorrar;
    conexion con = new conexion();
    Connection cn = con.conexion();
    DefaultTableModel modelo;

    public alta() {
        initComponents();
        this.setLocationRelativeTo(null);

        cargar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPaterno = new javax.swing.JTextField();
        txtMaterno = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtPeriodo = new javax.swing.JTextField();
        btnDocumento = new javax.swing.JButton();
        txtCPdf = new javax.swing.JTextField();
        btnGrabar = new javax.swing.JButton();
        jcFolio = new javax.swing.JCheckBox();
        jcMatricula = new javax.swing.JCheckBox();
        jcPlantel = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtBperiodo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtBnombre = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtBpaterno = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtBmaterno = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        txtBplantel = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnCertificado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sistema de Captura de Certificados");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setText("Folio");

        txtFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFolioActionPerformed(evt);
            }
        });

        jLabel11.setText("Matricula");

        jLabel12.setText("Nombre");

        jLabel13.setText("Paterno");

        jLabel14.setText("Materno");

        jLabel15.setText("Plantel");

        jLabel16.setText("Periodo");

        btnDocumento.setText("Documento");
        btnDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocumentoActionPerformed(evt);
            }
        });

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        jcFolio.setText("Sin Folio");

        jcMatricula.setText("Sin Matricula");

        jcPlantel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "AGUSTIN MELGAR", "AMADO NERVO", "BELISARIO DOMINGUEZ PALENCIA", "EMILIANO ZAPATA", "GABINO PALMA", "HEROES DE INDEPENDENCIA", "IESE", "INDEPENDENCIA CARMEN TEQUEXQUITLA", "INSTITUTO PAIDEIA", "JOSE MARIA MORELOS", "MIGUEL HIDALGO", "PREPARATORIA DE PUEBLA", "TRINIDAD SANTOS", " ", " ", " ", " " }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(126, 126, 126)
                                .addComponent(jLabel13))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jcFolio)
                                .addGap(27, 27, 27)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcMatricula)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnGrabar)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addGap(18, 18, 18)
                                            .addComponent(jcPlantel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(108, 108, 108))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jLabel14)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnDocumento)
                                .addGap(7, 7, 7)
                                .addComponent(txtCPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(txtPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcFolio)
                    .addComponent(jcMatricula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jcPlantel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGrabar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDocumento)
                        .addComponent(txtCPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda de Alumno"));

        jLabel18.setText("Plantel");

        jLabel19.setText("Periodo");

        jLabel20.setText("Nombre");

        jLabel21.setText("Paterno");

        jLabel22.setText("Materno");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBplantel, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBperiodo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBpaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(txtBperiodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txtBnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(txtBpaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(txtBmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBplantel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel23.setText("Total");

        txtTotal.setText("0");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Herramientas"));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnCertificado.setText("Certificado");
        btnCertificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCertificadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnModificar)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar)
                .addGap(18, 18, 18)
                .addComponent(btnBorrar)
                .addGap(18, 18, 18)
                .addComponent(btnCertificado)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCertificado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(txtTotal))
                    .addComponent(btnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFolioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFolioActionPerformed

    private void btnDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocumentoActionPerformed
        //creamos el objeto para el pdf
        JFileChooser pdfDigital = new JFileChooser();
        int option = pdfDigital.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            String pdfSeleccion = pdfDigital.getSelectedFile().getPath();
            txtCPdf.setText(pdfSeleccion);
        }

    }//GEN-LAST:event_btnDocumentoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        btnActualizar.setEnabled(true);
        limpiar();
        int fila = tabla.getSelectedRow();
        if (fila >= 0) {

            txtFolio.setText(tabla.getValueAt(fila, 2).toString());
            txtMatricula.setText(tabla.getValueAt(fila, 3).toString());
            txtNombre.setText(tabla.getValueAt(fila, 4).toString());
            txtPaterno.setText(tabla.getValueAt(fila, 5).toString());
            txtMaterno.setText(tabla.getValueAt(fila, 6).toString());

            txtPeriodo.setText(tabla.getValueAt(fila, 8).toString());

        } else {

        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String[] titulos = {"id", "Numero", "Folio", "Matricula", "Nombre", "Paterno", "Materno", "Plantel", "Generacion"};
        String[] registros = new String[9];
        String sql = "SELECT * FROM alumno WHERE (nombre like '%" + txtBnombre.getText() + "%')"
                + "and (paterno like '%" + txtBpaterno.getText() + "%')"
                + "and (materno like '%" + txtBmaterno.getText() + "%')"
                + "and (plantel like '%" + txtBplantel.getText() + "%')"
                + "and (periodo like '%" + txtBperiodo.getText() + "%')";

        modelo = new DefaultTableModel(null, titulos);

        try {

            Statement table;
            table = cn.createStatement();
            ResultSet rs = table.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("id");
                registros[1] = rs.getString("numero");
                registros[2] = rs.getString("folio");
                registros[3] = rs.getString("matricula");
                registros[4] = rs.getString("nombre");
                registros[5] = rs.getString("paterno");
                registros[6] = rs.getString("materno");
                registros[7] = rs.getString("plantel");
                registros[8] = rs.getString("periodo");

                modelo.addRow(registros);

            }
            tabla.setModel(modelo);

        } catch (SQLException ex) {
            System.out.println("Sin poder ejecutar el query a la tabla");
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {
            PreparedStatement pps = cn.prepareStatement("UPDATE alumno SET nombre='" + txtNombre.getText() + "',"
                    + "paterno='" + txtPaterno.getText() + "',"
                    + "materno='" + txtMaterno.getText() + "',"
                    + "folio='" + txtFolio.getText() + "',"
                    + "matricula='" + txtMatricula.getText() + "',"
                    + "periodo='" + txtPeriodo.getText() + "' WHERE id=''");
            pps.executeUpdate();
            cargar();
            limpiar();
        } catch (SQLException ex) {
            Logger.getLogger(alta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        //pasamos a mayusculas
        txtNombre.setText(txtNombre.getText().toUpperCase());
        txtPaterno.setText(txtPaterno.getText().toUpperCase());
        txtMaterno.setText(txtMaterno.getText().toUpperCase());

        // se asigna un contador
        int contador = 0;
        String pdfInicio = null;
        String pdfFinal = null;
        String Folio = txtFolio.getText();
        String Matricula = txtMatricula.getText();

        if (jcFolio.isSelected()) {
                Folio = "SIN FOLIO";
            }
            if (jcMatricula.isSelected()) {
                Matricula = "SIN MATRICULA";
            }

        // se checa que no falten campos
        if (txtNombre.getText().equals("") || txtPaterno.getText().equals("") || txtCPdf.getText().equals("") || Folio.equals("") || Matricula.equals("") ) {
            JOptionPane.showMessageDialog(this, "te faltan datos por escribir");
        } else {
            
            try {
                String sql = "SELECT * FROM cobat where (nombre='" + txtNombre.getText() + "' and paterno='" + txtPaterno.getText() + "' "
                        + "and materno='" + txtMaterno.getText() + "' and periodo='" + txtPeriodo.getText() + "')";
                Statement st;
                st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    contador++;
                }

            } catch (Exception e) {
            }

            if (contador > 1) {
                JOptionPane.showMessageDialog(this, "alumno repetido");
            } else {

                //Integramos en la BD el nuevo alumno
                PreparedStatement pps;
                try {
                    numerador numerar=new numerador();
                    String Plantel=jcPlantel.getSelectedItem().toString();
                    String Periodo=txtPeriodo.getText();
                    String numero=numerar.numero(Plantel,Periodo);
                    pps = cn.prepareStatement("INSERT INTO cobat (numero,folio,matricula,nombre,paterno,materno,plantel,periodo) "
                            + "VALUES (?,?,?,?,?,?,?,?)");
                    pps.setString(1, numero);
                    pps.setString(2, Folio);
                    pps.setString(3, Matricula);
                    pps.setString(4, txtNombre.getText());
                    pps.setString(5, txtPaterno.getText());
                    pps.setString(6, txtMaterno.getText());
                    pps.setString(7, jcPlantel.getSelectedItem().toString());
                    pps.setString(8, txtPeriodo.getText());
                    
                    pps.executeUpdate();

                } catch (SQLException ex) {
                    Logger.getLogger(alta.class.getName()).log(Level.SEVERE, null, ex);
                }
                //ya que se genero el alumno el cobat se obtiene su id cobat
                
                String sql = "SELECT * FROM cobat where (nombre='" + txtNombre.getText() + "' and paterno='" + txtPaterno.getText() + "' "
                        + "and materno='" + txtMaterno.getText() + "' and periodo='" + txtPeriodo.getText() + "')";

                try {
                    Statement st;
                    st = cn.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                    while (rs.next()) {

                        String txtPlantel = jcPlantel.getSelectedItem().toString();
                        try {
                            pdfInicio = txtCPdf.getText();
                            pdfFinal = "c:\\sicap\\" + txtPlantel + "\\" + rs.getString("idCobat") + ".pdf";
                            File inFile = new File(pdfInicio);
                            File outFile = new File(pdfFinal);

                            FileInputStream in = new FileInputStream(inFile);
                            FileOutputStream out = new FileOutputStream(outFile);

                            int c;
                            while ((c = in.read()) != -1) {
                                out.write(c);
                            }

                            in.close();
                            out.close();
                            inFile.delete();
                                                        
                            JOptionPane.showMessageDialog(null, "certificado integrado bien a la base de datos");
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, "no se grabo el certificado, error en subdirectorios");
                        }
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(alta.class.getName()).log(Level.SEVERE, null, ex);
                }

                cargar();
                limpiar();
            }
        }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        try {
            // salir del sistema
            cn.close();
        } catch (SQLException ex) {
            Logger.getLogger(alta.class.getName()).log(Level.SEVERE, null, ex);
        }
        Portada frm = new Portada();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCertificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCertificadoActionPerformed
         //mostrar PDF

        int fila = tabla.getSelectedRow();
        if (fila>=0){
            try {
                String sql="SELECT * FROM cobat WHERE (folio='"+tabla.getValueAt(fila, 0).toString()+"') and (matricula='"+
                tabla.getValueAt(fila, 1).toString()+"')and (plantel='"+
                tabla.getValueAt(fila, 5).toString()+"')and (periodo='"+
                tabla.getValueAt(fila, 6).toString()+"')and (nombre='"+
                tabla.getValueAt(fila, 2).toString()+"')and (paterno='"+
                tabla.getValueAt(fila, 3).toString()+"')and (materno='"+
                tabla.getValueAt(fila, 4).toString()+"')";
                System.out.println (sql);
                Statement st;
                st = cn.createStatement();
                ResultSet rs=st.executeQuery(sql);
                while (rs.next()){
                    File path = new File ("c:/sicap/"+rs.getString("plantel")+"/"+rs.getString("idCobat")+".pdf");
                    
                    try {
                        Desktop.getDesktop().open(path);
                    } catch (IOException ex) {
                        Logger.getLogger(Digitalizados.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
            catch (SQLException ex) {
                Logger.getLogger(Digitalizados.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

      
    }//GEN-LAST:event_btnCertificadoActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed

        int fila = tabla.getSelectedRow();
        if (fila >= 0) {
            idBorrar = tabla.getValueAt(fila, 0).toString();

        } else {

        }
        try {
            String sql = "DELETE FROM alumno WHERE id='" + idBorrar + "'";
            Statement st;
            st = cn.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Elemento Eliminado");

            limpiar();
            cargar();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "no se elimino el elemento");
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    void limpiar() {
        jcFolio.setSelected(false);
        jcMatricula.setSelected(false);
        txtFolio.setText("");
        txtMatricula.setText("");
        txtNombre.setText("");
        txtPaterno.setText("");
        txtMaterno.setText("");

        txtPeriodo.setText("");
        txtCPdf.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alta().setVisible(true);
            }
        });
    }

    //mostrar tabla
    void cargar() {
        // se crea una matriz para almacenar los datos
        total = 0;
        String[] cabecera = {"Numero","Folio", "Matricula", "Nombre", "Paterno", "Materno", "Plantel", "Generacion"};
        // se definen los registros que llevara la tabla
        String[] registros = new String[8];
        // se hace el llamado sql de todos los usuarios
        String sql = "SELECT * FROM cobat ORDER BY idCobat DESC";
        //establecemos los anchos en pixeles de las columnas
        int[] anchos = {100,150, 150, 200, 200, 200, 100, 100};
        modelo = new DefaultTableModel(null, cabecera);

        try {

            Statement table;
            table = cn.createStatement();
            ResultSet rs = table.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("numero");
                registros[1] = rs.getString("folio");
                registros[2] = rs.getString("matricula");
                registros[3] = rs.getString("nombre");
                registros[4] = rs.getString("paterno");
                registros[5] = rs.getString("materno");
                registros[6] = rs.getString("plantel");
                registros[7] = rs.getString("periodo");
                total++;

                modelo.addRow(registros);

            }
            tabla.setModel(modelo);
            for (int i = 0; i < cabecera.length; i++) {
                tabla.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
                tabla.setFont(new java.awt.Font("Tahoma", 0, 12));
            }

            txtTotal.setText(Integer.toString(total));
        } catch (SQLException ex) {
            System.out.println("Sin poder ejecutar el query a la tabla");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCertificado;
    private javax.swing.JButton btnDocumento;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jcFolio;
    private javax.swing.JCheckBox jcMatricula;
    private javax.swing.JComboBox<String> jcPlantel;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtBmaterno;
    private javax.swing.JTextField txtBnombre;
    private javax.swing.JTextField txtBpaterno;
    private javax.swing.JTextField txtBperiodo;
    private javax.swing.JTextField txtBplantel;
    private javax.swing.JTextField txtCPdf;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtMaterno;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPaterno;
    private javax.swing.JTextField txtPeriodo;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
