
package GUI;


import java.awt.Desktop;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.conexion;


public class alta extends javax.swing.JFrame {
    
    int conteo;
    int total;
    int limite;
    String idBorrar;
    conexion con=new conexion();
    Connection cn=con.conexion();
    DefaultTableModel modelo;
      
    public alta() {
        initComponents();
        this.setLocationRelativeTo(null);
        mostrarEstudiante();
        cargar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtCfolio = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCmatricula = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCnombre = new javax.swing.JTextField();
        txtCpaterno = new javax.swing.JTextField();
        txtCmaterno = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtCPeriodo = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        txtCPdf = new javax.swing.JTextField();
        btnGrabar = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtBperiodo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtBnombre = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtBpaterno = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtBmaterno = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        txtBplantel = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnCertificado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sistema de Captura de Certificados");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setText("Folio");

        txtCfolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCfolioActionPerformed(evt);
            }
        });

        jLabel11.setText("Matricula");

        jLabel12.setText("Nombre");

        jLabel13.setText("Paterno");

        jLabel14.setText("Materno");

        jLabel15.setText("Plantel");

        jLabel16.setText("Periodo");

        jButton4.setText("Documento");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Sin Folio");

        jCheckBox2.setText("Sin Matricula");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "AGUSTIN MELGAR", "AMADO NERVO", "BELISARIO DOMINGUEZ PALENCIA", "EMILIANO ZAPATA", "GABINO PALMA", "HEROES DE INDEPENDENCIA", "IESE", "INDEPENDENCIA CARMEN TEQUEXQUITLA", "INSTITUTO PAIDEIA", "JOSE MARIA MORELOS", "MIGUEL HIDALGO", "PREPARATORIA DE PUEBLA", "TRINIDAD SANTOS", " ", " ", " ", " " }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(7, 7, 7)
                        .addComponent(txtCPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(126, 126, 126)
                                .addComponent(jLabel13))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtCfolio, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox1)
                                .addGap(27, 27, 27)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBox2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnGrabar)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addGap(18, 18, 18)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(108, 108, 108))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jLabel14)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(txtCpaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCfolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtCmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtCPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(txtCPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda de Alumno"));

        jLabel18.setText("Plantel");

        jLabel19.setText("Periodo");

        jLabel20.setText("Nombre");

        jLabel21.setText("Paterno");

        jLabel22.setText("Materno");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBplantel, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBperiodo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBpaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(txtBperiodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txtBnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(txtBpaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(txtBmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBplantel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel23.setText("Total");

        txtTotal.setText("0");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Herramientas"));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnCertificado.setText("Certificado");
        btnCertificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCertificadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnModificar)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar)
                .addGap(18, 18, 18)
                .addComponent(btnBorrar)
                .addGap(18, 18, 18)
                .addComponent(btnCertificado)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCertificado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(txtTotal)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCfolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCfolioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCfolioActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //creamos el objeto para el pdf
      JFileChooser pdfDigital = new JFileChooser();
      int option=pdfDigital.showOpenDialog(this);
      if (option==JFileChooser.APPROVE_OPTION){
        String pdfSeleccion=pdfDigital.getSelectedFile().getPath();
        txtCPdf.setText(pdfSeleccion);
    }
      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
        btnActualizar.setEnabled(true);
        limpiar();
        int fila = tabla.getSelectedRow();
       if (fila>=0){
           
           txtCfolio.setText(tabla.getValueAt(fila, 2).toString());
           txtCmatricula.setText(tabla.getValueAt(fila, 3).toString());
           txtCnombre.setText(tabla.getValueAt(fila, 4).toString());
           txtCpaterno.setText(tabla.getValueAt(fila, 5).toString());
           txtCmaterno.setText(tabla.getValueAt(fila, 6).toString());
           
           txtCPeriodo.setText(tabla.getValueAt(fila, 8).toString());
           
       }
       else{
           
       }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       String[] titulos={"id","Numero","Folio","Matricula","Nombre","Paterno","Materno","Plantel","Generacion"};
       String[] registros = new String [9];
       String sql="SELECT * FROM alumno WHERE (nombre like '%"+txtBnombre.getText()+"%')"+
               "and (paterno like '%"+txtBpaterno.getText()+"%')"+
               "and (materno like '%"+txtBmaterno.getText()+"%')"+
               "and (plantel like '%"+txtBplantel.getText()+"%')"+
               "and (periodo like '%"+txtBperiodo.getText()+"%')";
       
       modelo = new DefaultTableModel(null,titulos);
       
              
       try {
       
       Statement table;
       table = cn.createStatement();
       ResultSet rs=table.executeQuery(sql);
       while (rs.next()){
           registros[0]=rs.getString("id");
           registros[1]=rs.getString("numero");
           registros[2]=rs.getString("folio");
           registros[3]=rs.getString("matricula");
           registros[4]=rs.getString("nombre");
           registros[5]=rs.getString("paterno");
           registros[6]=rs.getString("materno");
           registros[7]=rs.getString("plantel");
           registros[8]=rs.getString("periodo");
           
           modelo.addRow(registros);
           
       }
       tabla.setModel(modelo);
  
       
       
       
                
        
    
       }
       catch (SQLException ex){
           System.out.println ("Sin poder ejecutar el query a la tabla");
       }
 
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {
            PreparedStatement pps = cn.prepareStatement("UPDATE alumno SET nombre='"+txtCnombre.getText()+"',"+
                    "paterno='"+txtCpaterno.getText()+"',"+
                    "materno='"+txtCmaterno.getText()+"',"+
                   
                    "folio='"+txtCfolio.getText()+"',"+
                    "matricula='"+txtCmatricula.getText()+"',"+
                    
                    "periodo='"+txtCPeriodo.getText()+"' WHERE id=''");
            pps.executeUpdate();
            cargar();
            limpiar();
        } catch (SQLException ex) {
            Logger.getLogger(alta.class.getName()).log(Level.SEVERE, null, ex);
        }
              
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        // se asigna un contador
        int contador=0;
        String pdfInicio = null;
        String pdfFinal = null;

            // se checa que no falten campos
        if (txtCmatricula.getText().equals("") || txtCnombre.getText().equals("") || txtCPdf.getText().equals("")){
            JOptionPane.showMessageDialog(null,"te faltan datos por escribir");
        }else{
            
            try {
                // se prepara a insertar datos
                String sql="SELECT * FROM alumno WHERE (matricula='"+txtCmatricula.getText()+"')";
                Statement st;
                st = cn.createStatement();
                ResultSet rs=st.executeQuery(sql);
               
                while (rs.next()){
                    JOptionPane.showMessageDialog(null,"El registro esta repetido en la base de datos");
                    contador++;
                }
            } catch (SQLException ex) {
                Logger.getLogger(alta.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (contador==0){
            try {
                try {
			pdfInicio=txtCPdf.getText();
                        //pdfFinal="c:\\sicap\\certificados\\"+txtCplantel.getText()+"\\"+txtCPeriodo.getText()+"\\"+txtCnumero.getText()+
                          //      "-"+txtCmatricula.getText()+".pdf";
                        File inFile = new File(pdfInicio);
			File outFile = new File(pdfFinal);

			FileInputStream in = new FileInputStream(inFile);
			FileOutputStream out = new FileOutputStream(outFile);

			int c;
			while( (c = in.read() ) != -1)
				out.write(c);

			in.close();
			out.close();
                        inFile.delete();
                        JOptionPane.showMessageDialog(null,"certificado integrado bien a la base de datos");
                    } catch(Exception e) {
			JOptionPane.showMessageDialog(null,"no se grabo el certificado, error en subdirectorios");
		}
                
                PreparedStatement pps=cn.prepareStatement("INSERT INTO alumno (numero,folio,matricula,nombre,paterno,materno,plantel,periodo,imagen) "+
                    "VALUES (?,?,?,?,?,?,?,?,?)");
           // pps.setString(1,txtCnumero.getText());
            pps.setString(2,txtCfolio.getText());
            pps.setString(3,txtCmatricula.getText());
            pps.setString(4,txtCnombre.getText());
            pps.setString(5,txtCpaterno.getText());
            pps.setString(6,txtCmaterno.getText());
          //  pps.setString(7,txtCplantel.getText());
            pps.setString(8,txtCPeriodo.getText());
           // String imagen=txtCnumero.getText()+"-"+txtCmatricula.getText();
           // pps.setString(9,imagen);
            pps.executeUpdate();
            
            
            
            
            
            
            cargar();
            limpiar();
        } catch (SQLException ex) {
            Logger.getLogger(alta.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        try {
            // salir del sistema
            cn.close();
        } catch (SQLException ex) {
            Logger.getLogger(alta.class.getName()).log(Level.SEVERE, null, ex);
        }
        Portada frm=new Portada();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCertificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCertificadoActionPerformed
        //mostrar PDF
        
       int fila = tabla.getSelectedRow();
       if (fila>=0){
            try {
            String sql="SELECT * FROM alumno WHERE (folio='"+tabla.getValueAt(fila, 2).toString()+"') and (matricula='"+
                    tabla.getValueAt(fila, 3).toString()+"')and (numero='"+
                    tabla.getValueAt(fila, 1).toString()+"')and (plantel='"+
                    tabla.getValueAt(fila, 7).toString()+"')and (periodo='"+
                    tabla.getValueAt(fila, 8).toString()+"')";
            Statement st;
            st = cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while (rs.next()){
            File path = new File ("c:/sicap/certificados/"+rs.getString("plantel")+"/"+rs.getString("periodo")+"/"+
                rs.getString("numero")+"-"+rs.getString("matricula")+".pdf");
            //System.out.println ("c:/sicap/certificados/"+rs.getString("plantel")+"/"+rs.getString("periodo")+"/"+
            //        rs.getString("numero")+"-"+rs.getString("matricula")+".pdf");
                try {
                    Desktop.getDesktop().open(path);
                } catch (IOException ex) {
                    Logger.getLogger(alta.class.getName()).log(Level.SEVERE, null, ex);
                }
    
        
    }
    }
           catch (SQLException ex) {
                Logger.getLogger(alta.class.getName()).log(Level.SEVERE, null, ex);
    }
           
       }
       else{
           
       }
    }//GEN-LAST:event_btnCertificadoActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        
        int fila = tabla.getSelectedRow();
       if (fila>=0){
           idBorrar=tabla.getValueAt(fila, 0).toString();
           
           
       }
       else{
           
       }
        try{
            String sql="DELETE FROM alumno WHERE id='"+idBorrar+"'";
            Statement st;
            st=cn.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Elemento Eliminado");
            mostrarEstudiante();
            limpiar();
            cargar();
        }
        catch (Exception ex){
          JOptionPane.showMessageDialog(null,"no se elimino el elemento");
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    void limpiar(){
        
        txtCfolio.setText("");
        txtCmatricula.setText("");
        txtCnombre.setText("");
        txtCpaterno.setText("");
        txtCmaterno.setText("");
        
        txtCPeriodo.setText("");
        txtCPdf.setText("");
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alta().setVisible(true);
            }
        });
    }
    
    public void mostrarEstudiante(){
        
        // lee los estudiantes de la previa base de datos
        try {
           String sql="SELECT * FROM estudiante ORDER By id DESC ";
           Statement st;
           st = cn.createStatement();
           ResultSet rs=st.executeQuery(sql);
            while (rs.next()){
                /*
               txtId.setText(rs.getString("id"));
               conteo=Integer.parseInt(rs.getString("id"));
               limite=Integer.parseInt(rs.getString("id"));
               txtFolio.setText(rs.getString("folio"));
               txtMatricula.setText(rs.getString("matricula"));
               txtNombre.setText(rs.getString("nombre"));
               txtPaterno.setText(rs.getString("paterno"));
               txtMaterno.setText(rs.getString("materno"));
               txtPlantel.setText(rs.getString("plantel"));
               txtPeriodo.setText(rs.getString("periodo"));
               btnGrabar.setEnabled(false);
*/
        btnActualizar.setEnabled(false);
               
           }
        } catch (SQLException ex) {
            Logger.getLogger(alta.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }
    
    //mostrar tabla
    
    void cargar(){
      // se crea una matriz para almacenar los datos
      total=0;  
      String[] cabecera={"id","Numero","Folio","Matricula","Nombre","Paterno","Materno","Plantel","Generacion"};
        // se definen los registros que llevara la tabla
      String[] registros=new String[9];
        // se hace el llamado sql de todos los usuarios
      String sql="SELECT * FROM alumno ORDER BY id DESC";
        //establecemos los anchos en pixeles de las columnas
      int[] anchos={0,80,150,150,200,200,200,100,100};
        modelo= new DefaultTableModel(null,cabecera);
        
      try {
       
       Statement table;
       table = cn.createStatement();
       ResultSet rs=table.executeQuery(sql);
       while (rs.next()){
            registros[0]=rs.getString("id");
           registros[1]=rs.getString("numero");
           registros[2]=rs.getString("folio");
           registros[3]=rs.getString("matricula");
           registros[4]=rs.getString("nombre");
           registros[5]=rs.getString("paterno");
           registros[6]=rs.getString("materno");
           registros[7]=rs.getString("plantel");
           registros[8]=rs.getString("periodo");
           total++;
           
           modelo.addRow(registros);
           
       }
       tabla.setModel(modelo);
       for (int i=0;i<cabecera.length;i++){
          tabla.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
          tabla.setFont(new java.awt.Font("Tahoma", 0, 12));
       }
       // asignamos la columna 0 para esconderla
       tabla.getColumnModel().getColumn(0).setMaxWidth(0);
       tabla.getColumnModel().getColumn(0).setMinWidth(0);
       tabla.getColumnModel().getColumn(0).setPreferredWidth(0);
       txtTotal.setText(Integer.toString(total));
       }
       catch (SQLException ex){
           System.out.println ("Sin poder ejecutar el query a la tabla");
       }
   }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCertificado;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtBmaterno;
    private javax.swing.JTextField txtBnombre;
    private javax.swing.JTextField txtBpaterno;
    private javax.swing.JTextField txtBperiodo;
    private javax.swing.JTextField txtBplantel;
    private javax.swing.JTextField txtCPdf;
    private javax.swing.JTextField txtCPeriodo;
    private javax.swing.JTextField txtCfolio;
    private javax.swing.JTextField txtCmaterno;
    private javax.swing.JTextField txtCmatricula;
    private javax.swing.JTextField txtCnombre;
    private javax.swing.JTextField txtCpaterno;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
